  version: '3.8'
  services:
    app:
      build: 
        dockerfile: docker/dev.Dockerfile
      ports:
        - "5173:5173"
      volumes:
        - ./:/app           
        - /app/node_modules
      stdin_open: true  
      tty: true 